
all:
	@cmd /C "cd windows & nmake /NOLOGO /f Makefile.vc all"
	@copy windows\*.exe C:\USR\PUTTY

clean:
	@cmd /C "cd windows & nmake /NOLOGO /f Makefile.vc clean"

# This is a tiny makefile for VS on Windows.
